// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXbsEOIE07RHAhiR1AxKw8UU-maVO80fQ',
    appId: '1:150520271583:web:c420bdfc5fbba25dafcf6a',
    messagingSenderId: '150520271583',
    projectId: 'youneswhatsapp-19dfa',
    authDomain: 'youneswhatsapp-19dfa.firebaseapp.com',
    databaseURL: 'https://youneswhatsapp-19dfa.firebaseio.com',
    storageBucket: 'youneswhatsapp-19dfa.appspot.com',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0CaM5GrksHxrGRWx17IscQoaLkbkSM1k',
    appId: '1:150520271583:android:c3cc0525a721c9aeafcf6a',
    messagingSenderId: '150520271583',
    projectId: 'youneswhatsapp-19dfa',
    databaseURL: 'https://youneswhatsapp-19dfa.firebaseio.com',
    storageBucket: 'youneswhatsapp-19dfa.appspot.com',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClrVTCudw9ul1AasZLwBY7ipp-Oyun0Cg',
    appId: '1:150520271583:ios:a9f542ccae22900dafcf6a',
    messagingSenderId: '150520271583',
    projectId: 'youneswhatsapp-19dfa',
    databaseURL: 'https://youneswhatsapp-19dfa.firebaseio.com',
    storageBucket: 'youneswhatsapp-19dfa.appspot.com',
    androidClientId: '150520271583-ar3b2282j73bpo1u5lh2evf70uu7412i.apps.googleusercontent.com',
    iosClientId: '150520271583-4v5delkv0nprfu17fkssvq5riqi1juc4.apps.googleusercontent.com',
    iosBundleId: 'com.ymrabtiapps.thumbnails.thumbnailYoutube',
  );
}
